name: tool_mobile
description: Flutter Tools' base plus mobile. Use to create command line tools.
version: 3.0.0
homepage: https://github.com/mmcc007/tool_mobile

environment:
  sdk: '>=3.0.0'

dependencies:
  tool_base:
    git:
      ref: 950396e2795f77640276dd2ed73b83316f825191
      url: https://github.com/daniele-athome/tool_base.git

dev_dependencies:
  mockito: ^5.0.16
  pedantic: ^1.0.0
  test: ^1.16.6
